# High Power Rocketry - Flight Simulation
# GNU General Public License v3.0
# Copyright (C) 2019 Roshan Doddanavar
# https://rdoddanavar.github.io
# 
# ██╗  ██╗██████╗ ██████╗       ███████╗██╗███╗   ███╗
# ██║  ██║██╔══██╗██╔══██╗      ██╔════╝██║████╗ ████║
# ███████║██████╔╝██████╔╝█████╗███████╗██║██╔████╔██║
# ██╔══██║██╔═══╝ ██╔══██╗╚════╝╚════██║██║██║╚██╔╝██║
# ██║  ██║██║     ██║  ██║      ███████║██║██║ ╚═╝ ██║
# ╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝      ╚══════╝╚═╝╚═╝     ╚═╝
# 
# Path:
#     hpr-sim/src/util/config_unit.yaml
# Created:
#     2019-05-24
# Type:
#     YAML config file
# Description:
#     Provides unit conversion factors relative to a default unit for a given measurement type
# Functions:
#     None
# Classes:
#     None
# Dependencies:
#     hpr-sim/src/util/unit_convert.py
---
default:
    time: s
    length: m
time: 
    ms: 1.0e-3
    s: 1.0
    min: 60
    h: 3600
length:
    mm: 1.0e-3
    cm: 1.0e-2
    m: 1.0
    km: 1.0e+3
    in: 0.0254
    ft: 0.3048
    mi: 1609.34
...