#------------------------------------------------------------#
# High Power Rocketry - Flight Simulation
# GNU General Public License v3.0
# Roshan Doddanavar
# https://rdoddanavar.github.io
#------------------------------------------------------------#
#     ___       ___       ___       ___       ___       ___
#    /\__\     /\  \     /\  \     /\  \     /\  \     /\__\  
#   /:/__/_   /::\  \   /::\  \   /::\  \   _\:\  \   /::L_L_
#  /::\/\__\ /::\:\__\ /::\:\__\ /\:\:\__\ /\/::\__\ /:/L:\__\
#  \/\::/  / \/\::/  / \;:::/  / \:\:\/__/ \::/\/__/ \/_/:/  /
#    /:/  /     \/__/   |:\/__/   \::/  /   \:\__\     /:/  /
#    \/__/               \|__|     \/__/     \/__/     \/__/  
# 
#------------------------------------------------------------#
# Path:
#     hpr-sim/src/preproc/config_param.yaml
# Created:
#     2019-05-21
# Type:
#     YAML config file
# Description:
#     Provides default values for input param fields
# Input:
#     None
# Output:
#     None
# Dependencies:
#     hpr-sim/src/preproc/input.cpp
#                        /input.h
#------------------------------------------------------------#
---
sim:
    numMC:
        min: 0
        max: .inf    
    seedMaster:
        min: 0
        max: 32767
...