# <header>
---
telem:
 - time
 - thrust
 - isBurnout
 - massEng
 - mass
 - gravity
 - temperature
 - pressure
 - density
 - dynamicPressure
 - mach
 - alphaT
 - dragCoeff
 - dragForce
 - liftForce
 - forceZB
 - x
 - y
 - z
# stats
# time: max
# etc.
# TODO: populate stats and specific min, max, mean, stdDev, etc.