# <header>
---
telem:
 - time
 - thrust
 - massEng
 - mass
 - gravity
 - temperature
 - pressure
 - density
 - forceZ
 - linAccZ
 - linVelZ
 - linPosZ
# stats
# time: max
# etc.
# TODO: populate stats and specific min, max, mean, stdDev, etc.