# High Power Rocketry - Flight Simulation
# MIT License
# Copyright (C) 2019 Roshan Doddanavar
# https://rdoddanavar.github.io
# 
# Path:
#     hpr-sim/src/util/config_unit.yaml
# Created:
#     2019-05-24
# Type:
#     YAML config file
# Description:
#     Provides unit conversion factors relative to a default unit for a given measurement type
# Functions:
#     None
# Classes:
#     None
# Dependencies:
#     hpr-sim/src/util/unit_convert.py
---
default:
    time: s
    length: m
    area: m^2
    volume: m^3
    velocity: m/s
    acceleration: m/s^2
    mass: kg
    density: kg/m^2
    energy: J
    force: N
    moment: N*m
    intertia: kg*m^2
    pressure: Pa
    angle: rad
    angular-rate: rad/s
    angular-aceleration: rad/s^2
time: 
    ms: 1.0e-3
    s: 1.0
    min: 60
    h: 60*60
length:
    mm: 1.0e-3
    cm: 1.0e-2
    m: 1.0
    km: 1.0e+3
    in: 0.3048/12
    ft: 0.3048
    mi: 5280*0.3048
temperature: # [factor, offset]
    K: [1.0, 0.0]
    C: [1.0, 273.15]
    R: [5/9, 0]
    F: [5/9, -32*(5/9) + 273.15]
...