# High Power Rocketry - Flight Simulation
# GNU General Public License v3.0
# Copyright (C) 2019 Roshan Doddanavar
# https://rdoddanavar.github.io
# 
# ██╗  ██╗██████╗ ██████╗       ███████╗██╗███╗   ███╗
# ██║  ██║██╔══██╗██╔══██╗      ██╔════╝██║████╗ ████║
# ███████║██████╔╝██████╔╝█████╗███████╗██║██╔████╔██║
# ██╔══██║██╔═══╝ ██╔══██╗╚════╝╚════██║██║██║╚██╔╝██║
# ██║  ██║██║     ██║  ██║      ███████║██║██║ ╚═╝ ██║
# ╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝      ╚══════╝╚═╝╚═╝     ╚═╝
# 
# Path:
#     hpr-sim/src/preproc/config_param.yaml
# Created:
#     2019-05-21
# Type:
#     YAML config file
# Description:
#     Provides default values for input param fields
# Functions:
#     None
# Classes:
#     None
# Dependencies:
#     None
---
exec:
    seedMaster:
        quantity: null
        unit: null
        min: 0.0
        max: .inf
    numMC:
        quantity: null
        unit: null
        min: 0.0
        max: .inf
    numProc:
        quantity: null
        unit: null
        min: 0.0
        max: .inf
    timeFlight:
        quantity: time
        unit: s
        min: 0.0
        max: .inf
    timeStep:
        quantity: time
        unit: s
        min: 0.0
        max: .inf
    numProc:
        quantity: null
        unit: null
        min: 0.0
        max: .inf
mass:
    massBody:
        quantity: mass
        unit: kg
        min: 0.0
        max: .inf
geodetic:
    latitude:
        quantity: angle
        unit: deg
        min: -90.0
        max: 90.0
engine:
    inputPath:
        isPath: true
...