# High Power Rocketry - Flight Simulation
# GNU General Public License v3.0
# Copyright (C) 2019 Roshan Doddanavar
# https://rdoddanavar.github.io
# 
# ██╗  ██╗██████╗ ██████╗       ███████╗██╗███╗   ███╗
# ██║  ██║██╔══██╗██╔══██╗      ██╔════╝██║████╗ ████║
# ███████║██████╔╝██████╔╝█████╗███████╗██║██╔████╔██║
# ██╔══██║██╔═══╝ ██╔══██╗╚════╝╚════██║██║██║╚██╔╝██║
# ██║  ██║██║     ██║  ██║      ███████║██║██║ ╚═╝ ██║
# ╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝      ╚══════╝╚═╝╚═╝     ╚═╝
# 
# Path:
#     hpr-sim/src/preproc/config_param.yaml
# Created:
#     2019-05-21
# Type:
#     YAML config file
# Description:
#     Provides default values for input param fields
# Functions:
#     None
# Classes:
#     None
# Dependencies:
#     None
---
exec:
    mode:
        type: str
        isPath: false
        valid: [nominal, montecarlo]
    seed:
        type: int
        quantity: null
        unit: null
        min: 0
        max: .inf
    numMC:
        type: int
        quantity: null
        unit: null
        min: 0
        max: .inf
    numProc:
        type: int
        quantity: null
        unit: null
        min: 0
        max: .inf
flight:
    timeFlight:
        type: float
        quantity: time
        unit: s
        min: 0.0
        max: .inf
    timeStep:
        type: float
        quantity: time
        unit: s
        min: 0.0
        max: .inf
engine:
    inputPath:
        type: str
        isPath: true
mass:
    massBody:
        type: float
        quantity: mass
        unit: kg
        min: 0.0
        max: .inf
geodetic:
    latitude:
        type: float
        quantity: angle
        unit: rad
        min: -3.14159265359/2
        max: 3.14159265359/2
    altitude:
        type: float
        quantity: length
        unit: m
        min: 0.0
        max: .inf
atmosphere:
    temperature:
        type: float
        quantity: temperature
        unit: K
        min: 0.0
        max: .inf
    pressure:
        type: float
        quantity: pressure
        unit: Pa
        min: 0.0
        max: .inf
aerodynamics:
    inputPath:
        type: str
        isPath: true
    refArea:
        type: float
        quantity: area
        unit: m^2
        min: 0.0
        max: .inf
...