name: build-test
on: push
jobs:
    build-ubuntu:
        runs-on: ubuntu-20.04
        defaults:
            run:
                working-directory: ./build
        steps:
            - uses: actions/checkout@v2
            - name: Configure Build
              run: cmake ../
            - name: Execute Build
              run: make