name: build-test
on: push
jobs:
    build-ubuntu:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - run: cd ./build
            - run: cmake ../
            - run: make