name: unit-test-ubuntu
on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Configure build
        run: cd build && cmake --preset ubuntu ../
      - name: Execute build
        run: cd build && cmake --build . -j
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ github.workflow }}-${{ github.sha }}
  test-ubuntu:
    runs-on: ubuntu-24.04
    needs: build-ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Retrieve build artifacts
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ github.workflow }}-${{ github.sha }}
      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install python packages
        run: pip install -r requirements.txt
      - name: Run unit test
        run: ./hpr-sim.py -i input/unit_test.yml -o output/ && ls -l output/*/*
      - name: Run regression test
        run: python tools/regression_test.py tools/unit_test/ubuntu output/unit_test output/diff
  pyinstaller-ubuntu:
    runs-on: ubuntu-24.04
    needs: build-ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Retrieve build artifacts
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ github.workflow }}-${{ github.sha }}
      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install python packages
        run: pip install -r requirements.txt
      - name: PyInstaller build
        run: python tools/pyinstaller_build.py
      - name: Run unit test
        run: cd build/pyinstaller/dist/hpr-sim && ./hpr-sim -i input/unit_test.yml -o output/ && ls -l output/*/*
      - name: Run regression test
        run: python tools/regression_test.py tools/unit_test/ubuntu build/pyinstaller/dist/hpr-sim/output/unit_test build/pyinstaller/dist/hpr-sim/output/diff
